- name: Specify MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='password' vtype='password'
  become: true

- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='password' vtype='password'
  become: true

- name: MySQL | install mysql packages
  apt: pkg={{ item }} state=installed
  become: true
  with_items:
   - mysql-client
   - mysql-server
   - php-mysql
